# Generated by Django 5.1.6 on 2025-03-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('m', 'Movie'), ('t', 'TV Series'), ('b', 'Board Game')], max_length=1)),
                ('release_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('creator', models.ManyToManyField(help_text='Select the creator(s) of this adaptation', to='catalog.author')),
            ],
        ),
    ]
