# Generated by Django 5.1.6 on 2025-03-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_adaptation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptation',
            name='media_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV Series', 'TV Series'), ('Board Game', 'Board Game')], max_length=100),
        ),
    ]
