# Generated by Django 5.1.6 on 2025-03-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_adaptation_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptation',
            name='media_type',
            field=models.CharField(choices=[('m', 'Movie'), ('t', 'TV Series'), ('b', 'Board Game')], max_length=1),
        ),
    ]
